# Generated by Django 4.2.16 on 2024-12-16 12:52

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("songs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recordedsongs",
            name="audio",
            field=models.FileField(
                storage=cloudinary_storage.storage.MediaCloudinaryStorage(),
                upload_to="choir-audio/",
            ),
        ),
    ]
